sns:
  label: 社交资料
  items:
    rss:
      name: rss
      label: RSS
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    twitter:
      name: twitter
      label: Twitter
      type: text
      placeholder: '只需填入 Twitter 用户名即可'
    facebook:
      name: facebook
      label: Facebook
      type: text
      placeholder: '只需填入 Facebook 用户名即可'
    instagram:
      name: instagram
      label: Instagram
      type: text
      placeholder: '只需填入 Instagram 用户名即可'
    dribbble:
      name: dribbble
      label: Dribbble
      type: text
      placeholder: '只需填入 Dribbble 用户名即可'
    weibo:
      name: weibo
      label: 微博
      type: text
      placeholder: '只需填入微博 Id 即可'
    email:
      name: email
      label: Email
      type: text
      placeholder: '只需填入邮箱地址即可'
    github:
      name: github
      label: Github
      type: text
      placeholder: '只需填入 Github 用户名即可'
    qq:
      name: qq
      label: QQ
      type: text
      placeholder: '只需填入 QQ 号即可'
    telegram:
      name: telegram
      label: Telegram
      type: text
      placeholder: '只需填入 Telegram Id 即可'