# 主题配置文件说明：https://docs.halo.run/zh/developer-guide/theme/config-files
base:
  label: '基本设置'
  items:
    dr_link:
      label: Dr.{ Link }
      type: text
      default: '/about'
      placeholder: 'URL'
      description: '侧边栏 Dr.{博主昵称} 跳转链接'
    canvas_dust:
      label: CanvasDust 效果
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 启用
        - value: false
          label: 禁用